In [82]:
import numpy as np

In [83]:
a = [1,2,3,4,5]

In [84]:
b = np.array(a)

In [85]:
b

array([1, 2, 3, 4, 5])

In [86]:
c = [[1,2,3],[4,5,6],[7,8,9]]

In [87]:
nested = np.array(c)

In [88]:
nested

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [90]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [91]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
# Evenly spaced elements (linearly space elements)
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [93]:
# Gen identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
# Generate array with uniform distribution (between 0 & 1)
# equally likely to be picked
np.random.rand(3,4)

array([[0.43233482, 0.66603658, 0.91475633, 0.10881782],
       [0.10591574, 0.57439251, 0.75575477, 0.23528479],
       [0.00191558, 0.51557978, 0.71434415, 0.10435191]])

In [95]:
# Same but with normal distribution (mean is 0 & variance is 1)
np.random.randn(5,5)

array([[-0.4003756 ,  1.34298705, -0.0122756 ,  1.03750425,  0.38271037],
       [ 1.71420973, -0.07139216,  1.03882166,  0.74312789,  0.10423255],
       [-0.30283703, -1.27076656, -0.38302395, -1.01325068,  0.77733487],
       [-0.19162043,  0.86623479,  1.05047121,  3.2954423 ,  2.02174768],
       [ 0.97213843,  0.49328902, -1.8137993 , -0.08209276,  1.01136943]])

In [96]:
# Generate random integer between range passed in 
# (inclusive, exclusive, num elements or shape as tuple) 
np.random.randint(1,100,3)


array([49, 30, 47])

In [97]:
np.random.randint(1,100,(2,3))

array([[43, 23, 85],
       [85, 62,  4]])

In [98]:
# We can get the .shape property of a numpy array
element = np.ones((10,5))
element.shape

(10, 5)

In [99]:
# We can also reshape it, so long as the total number
# of items does not changed

In [100]:
element.reshape((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
element.reshape((25,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [102]:
# Changes are not permanent unless you reassing
# the changes
element

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
element.shape

(10, 5)

In [104]:
element = element.reshape((5,10))

In [105]:
element

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [106]:
element.shape

(5, 10)

In [107]:
# We can also get min, max, argmax & minmax
element.max()

1.0

In [108]:
element.min()

1.0

In [109]:
# Give the index of the largest value
element.argmax()

0

In [81]:
element.argmin()

0

In [110]:
# Get data type
element.dtype

dtype('float64')