In [15]:
import numpy as np

In [16]:
array = np.arange(0,11)

In [17]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Numpy does ops on an element by elements basis
# Doing this adds 5 to every element of the array
array + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
# But the changes do not affect the actual array unless
# you re-declare them
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
array = array + 5

In [35]:
array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
# Restore array
array = array - 5
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# We can do mean, sqrt, sine, log, etc
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [38]:
np.log(array)

/Users/phaseon/anaconda3/envs/tfcourse/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [40]:
np.mean(array)

5.0

In [41]:
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

# Array method

In [43]:
array.sum()

55

In [44]:
array.max()

10

In [45]:
array.std()

3.1622776601683795

In [49]:
array2d = np.arange(0,25).reshape(5,5)

In [50]:
array2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
# Perform sum across rows
array2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [52]:
# Perform sum across cols

In [53]:
array2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])