In [1]:
import numpy as np
array = np.arange(0,11)

In [2]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Select a single value
array[2]

2

In [5]:
array[0:3]

array([0, 1, 2])

In [6]:
array[:4]

array([0, 1, 2, 3])

In [8]:
array[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

# Broadcasting

In [9]:
# Broadcasting, you can't do this with a python list
# You can reassign one value across multiple indexes quickly
array[0:5] = 100

In [10]:
array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Let's reset the array
array = np.arange(0,11)

In [12]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Slices work differently as well, here we slice
# indexes 0 through 5, 5 non inclusive
slice_of = array[0:5]
slice_of

array([0, 1, 2, 3, 4])

In [19]:
# But now, changing this slice also changes the original array
slice_of[:] = 100

In [20]:
# Notice how the change we made in the slice now is
# reflected in the original array
array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
# To block broadcasting we need to explicitly make a copy
# of the array
array_cpy = array.copy()

In [23]:
array_cpy[:] = 100
array_cpy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Indexing on 2D array

In [27]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [28]:
array2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
# Single element
array2d[1,1]

5

In [33]:
# Alternative format
array2d[1][1]

5

In [31]:
array2d.shape

(4, 3)

In [32]:
# Whole row
array2d[0]

array([1, 2, 3])

In [34]:
# Slice 
array2d[:2,1:3]

array([[2, 3],
       [5, 6]])

# Conditionals

In [35]:
array2 = np.arange(0,11)

In [36]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Conditionals return an array of booleans with true or
# depending on whether the element meets the conditional
# or not
array2 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [41]:
# We can use this resulting array of booleans as a filter
# by simply using it as "an index"
boolarr = array2 > 4

In [42]:
array2[boolarr]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
# An easier form of notation is putting the comparison
# directly where the index goes
array2[array2 > 5]

array([ 6,  7,  8,  9, 10])